name: Glossing Entries Deploy
on: 
  pull_request:
      branches:
        main
jobs:
  deploy:
    needs: merge-branch
    strategy: 
      matrix:
        machines: [vlcdhp02]
    runs-on: ${{ matrix.machines }}
    steps:
      - uses: actions/checkout@v3
      - run: |
          cd /opt/tomcat/webapps/glossing/
          git stash
          git checkout main
          git pull
          git checkout $GITHUB_HEAD_REF
          git pull